apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    # on enlève le préfixe /auth : /auth/xxx -> /xxx côté Keycloak
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /auth(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: keycloak-public   # ou 'keycloak' si c'est celui-là que tu utilises
            port:
              number: 80            # 80 pour keycloak-public, 8080 si tu pointes sur 'keycloak'
